name: Gloomygift
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36796
title: 'Art , inspiration and working progress'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#767676'
    - '#393939'
    - '#b9b9b9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
