name: gloomygift
favicon: null
layout_spectrum: 0.5003
typography_spectrum: 0.48248
title: 'art , inspiration and working progress'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#947384'
    - '#cbc7d6'
    - '#644b72'
    - '#9b98a3'
    - '#fff0ff'
  brandStrength: 0
  lightness: 0.2656546055804938
  saturation: 0.1678885198198259
  rhythmicContrast: 0.6941042945254594
purpose: []
