name: gloomygift
favicon: null
layout_spectrum: 0.9766919657122344
typography_spectrum: 0.48248
title: 'art , inspiration and working progress'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#000000'
    - '#bfb6a5'
    - '#f7190e'
    - '#2e6800'
  brandStrength: 0.0625
  lightness: 0.2656546055804938
  saturation: 0.1678885198198259
  rhythmicContrast: 0.6941042945254594
purpose: []
