name: Gloomygift
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22088
title: 'Art , inspiration and working progress'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfffe'
    - '#010101'
    - '#d8dad9'
    - '#3d3d3d'
    - '#838383'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
