name: Gloomygift
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22088
title: 'Art , inspiration and working progress'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3eadb'
    - '#020204'
    - '#6a6762'
    - '#aeaba6'
    - '#ccc8bc'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
